### PR TITLE
an update ? 0.o

### PR DESCRIPTION
**Pull request by 123callumb**
okay the workstatins/candy machines are now independent and you cannot customise workstations or the floor anymore...just because it makes it look ugly. Also the future plans to have a map of candy buildings and you dominate the world with candy, ya feel? okay good!

### CODE REVIEW

**Comment by Killiann** [comment]
Cool beans son 😎 so the shop
Is going to be exclusively for clothing?

On 3 Aug 2017, at 19:18, Callum Beckwith <notifications@github.com<mailto:notifications@github.com>> wrote:


Merged #135<https://github.com/123callumb/CandyIOS/pull/135>.

**Comment by 123callumb** [comment]
Clothes and desks :P

**Comment by Killiann** [comment]
Okay cool I might redo the shop a little bit if it's just clothes and desks

On 6 Aug 2017, at 20:27, Callum Beckwith <notifications@github.com<mailto:notifications@github.com>> wrote:


Clothes and desks :P

**Comment by 123callumb** [comment]
oh and sweet packets :P

**Pull request merged**
